---
- name: Test connectivity to switch
  hosts: all
  gather_facts: no
 
  tasks:
    - name: Gather basic device facts
      cisco.ios.ios_facts:
      register: facts_out
    - name: Print facts summary
      debug:
        var: facts_out.ansible_facts.net_model
