---
  - name: Check F5 is active or standalone
    import_playbook: f5_config_sync.yaml

  - name: VIP Validation task
    import_playbook: get_vip_list.yml
  
  - name: VIP Creation task
    import_playbook: create_vip.yml

  - name: Pool Creation task
    import_playbook: create_pool.yml

  - name: Pool Member Modification task
    import_playbook: update_pool_member.yml