---
- name: Extract availability state for ALL VIPs
  block:
    - name: VIP state of {{vip.name}}
      set_fact:
        vip_result: "VIP State of {{ vip.name }} - {{ vip.availability_status }}"
      register: vip_result
  rescue:
    - name: Handle failure for {{ vip.name }}
      set_fact:
        vip_result: "VIP name - {{ vip.name }} invalid"        
      register: vip_result

- name: Write result to log
  lineinfile:
    path: "{{ log_file }}"
    line: >
          "{{ '%Y-%m-%d %H:%M:%S' | strftime }} - {{ vip_result.ansible_facts.vip_result }}"
    insertafter: EOF