---
- name: Combine Server auth and pool creation dict
  set_fact:
    new_dict: "{{ item | ansible.builtin.combine({'provider': provider }) }}"
# - debug: msg="{{ new_dict }}"     

- name: Create Pool
  block:
  - name: Pool creation state of  {{new_dict.name}}
    bigip_pool: "{{ new_dict }}"
  rescue:
  - name: Handle failure for {{ new_dict.name }}
    debug: 
      msg: "Error creating pool - {{ new_dict.name  }}"
  notify: Config Sync (Manual Only)